### ISSUE TITLE
EAC instructions outdated

### ISSUE THREAD

**Issue by GrainySnapshot** [urbster1/mareo#2]
The configuration instructions for Exact Audio Copy appear not to be valid for versions of Exact Audio Copy post v1.0b2.  The correct entry for the "Additional command-line options" text box on the EAC "External Compression" tab (based solely on EAC documentation and without testing yet) would be:

mareo.ini %source% %dest% "%artist%" "%albumtitle%" "%title%" "%tracknr1%" %year% "%genre%"

NOT as stated in the Mareo Github documentation:

mareo.ini %s %d "%a" "%g" "%t" "%n" %y "%m"

The latter produces an error from EAC "invalid replacement tag found" upon clicking the OK button and presumably also would not work on running EAC.

**Comment by urbster1** [comment]
Thanks! I've updated the README to reflect this change.
